oauth2:
  openid:
    discovery:
      baseUri: http://127.0.0.1:8000
      issuer: http://127.0.0.1:8000/openid
      tokenEndpoint: http://127.0.0.1:8000/oauth/token
      tokenKeyEndpoint: http://127.0.0.1:8000/oauth/token_key
      userinfoEndpoint: http://127.0.0.1:8000/userinfo
      checkTokenEndpoint: http://127.0.0.1:8000/oauth/check_token
      revocationEndpoint: http://127.0.0.1:8000/oauth/revoke
      authorizationEndpoint: http://127.0.0.1:8000/oauth/authorize
      jwksUri: http://127.0.0.1:8000/openid/.well-known/jwks.json
      userinfoSigningAlgSupported:
        - RS256
      idTokenSigningAlgValuesSupported:
        - RS256
      tokenEndpointAuthSigningAlgorithmsSupported:
        - RS256
      scopesSupported:
        - openid
        - profile
        - email
        - read
        - write
      subjectTypesSupported:
        - public
        - pairwise
      responseTypesSupported:
        - code
        - token
      claimsSupported:
        - email
        - family_name
        - given_name
        - name
        - birthdate
        - iss
        - sub
        - iat
        - azp
        - exp
        - preffered_username
        - at_hash
        - c_hash
        - nonce
      grantTypesSupported:
        - authorization_code
      tokenEndpointAuthMethodsSupported:
        - client_secret_basic
        - client_secret_post
