server:
  port: 8000
spring:
  application:
    name: REX-AUTH
  data:
    mongodb:
      uri: ${MONGO_URI}
oauth2:
  server:
    resourceid: oauth2-server
  openid:
    baseUri: http://127.0.0.1:${server.port}
  implicit-enabled: true
