server:
  port: 9366
spring:
  application:
    name: REX-AUTH-TEST
  data:
    mongodb:
      database: authserver
      auto-index-creation: true

oauth2:
  server:
    resourceid: test-oauth2-server
  openid:
    discovery:
      baseUri: http://127.0.0.1:${server.port}
    implicit:
      enabled: true
