server:
  port: 8000
spring:
  application:
    name: REX-AUTH
  data:
    mongodb:
      username: idea
      password: ideapass
      database: authserver
      auto-index-creation: true

oauth2:
  openid:
    discovery:
      baseUri: http://127.0.0.1:8000
    implicit:
      enabled: true
