server:
  port: 8000
spring:
  application:
    name: REX-AUTH
  data:
    mongodb:
      username: idea
      password: ideapass
      database: authserver

#security:
#  oauth2:
#    authorization:
#      jwt:
logging:
  level:
    root: debug
#        key-value: