oauth2:
  openid:
    implicit:
      enabled: ${ENABLE_IMPLICIT_ID_TOKEN}
spring:
  application:
    name: AUTHENTICATION_SERVER
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: 27017
      auto-index-creation: true
